server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:dealership;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true

logging:
  level:
    org.springframework.security: INFO
