spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dealership}
    username: ${DB_USERNAME:Custodian}
    password: ${DB_PASSWORD:Custodian}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.security.provisioning.JdbcUserDetailsManager: DEBUG
    
server:
  port: 8080
